# Generated by Django 5.1.6 on 2025-03-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='brand', max_length=50)),
                ('type', models.CharField(default='type', max_length=50)),
                ('size', models.CharField(default='size', max_length=50)),
                ('transmission', models.CharField(default='trans', max_length=50)),
                ('fuelType', models.CharField(default='fuel', max_length=50)),
                ('isReserved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DSD400Project.car')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
