# Generated by Django 5.1.6 on 2025-02-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DSD400Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('isReserved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DSD400Project.cars')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DSD400Project.user')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='reservedByUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DSD400Project.user'),
        ),
    ]
