# Generated by Django 5.1.6 on 2025-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_available',
            new_name='isAvailable',
        ),
        migrations.RemoveField(
            model_name='car',
            name='isReserved',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Volvo', 'Volvo'), ('BMQ', 'BMW'), ('Audi', 'Audi')], default='Volvo', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('gas', 'gas'), ('electric', 'electric')], default='gas', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('big', 'big')], default='small', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Combi', 'Combi')], default='SUV', max_length=50),
        ),
    ]
