# Generated by Django 5.1.6 on 2025-02-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0002_initial'),
    ]

    operations = [
    ]
