# Generated by Django 5.1.6 on 2025-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0002_rename_is_available_car_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Volvo', 'Volvo'), ('BMQ', 'BMW'), ('Audi', 'Audi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('gas', 'gas'), ('electric', 'electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('big', 'big')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Combi', 'Combi')], max_length=50),
        ),
    ]
