# Generated by Django 5.1.6 on 2025-03-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0003_auto_20250227_1738'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('isReserved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='reservedByUserId',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DSD400Project.car'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
