# Generated by Django 5.1.6 on 2025-03-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0003_alter_car_brand_alter_car_fueltype_alter_car_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Volvo', 'Volvo'), ('BMW', 'BMW'), ('Audi', 'Audi')], max_length=50),
        ),
    ]
