# Generated by Django 5.1.6 on 2025-03-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0003_auto_20250227_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='type',
            new_name='FuelType',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='reservedByUserId',
        ),
    ]
