# Generated by Django 5.1.6 on 2025-03-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0004_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startDate',
            field=models.DateField(auto_now=True),
        ),
    ]
