# Generated by Django 5.1.6 on 2025-03-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0004_car_remove_cars_reservedbyuserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
