# Generated by Django 5.1.6 on 2025-03-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0005_car_fueltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default='placeholder', max_length=50),
        ),
    ]
