# Generated by Django 5.1.6 on 2025-03-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0006_alter_car_fueltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='brand', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default='fuel', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(default='size', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='trans', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(default='type', max_length=50),
        ),
    ]
