# Generated by Django 5.1.6 on 2025-03-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSD400Project', '0004_rename_type_cars_fueltype_and_more'),
        ('DSD400Project', '0007_remove_car_model_alter_car_brand_alter_car_fueltype_and_more'),
    ]

    operations = [
    ]
